// Code generated by tools/codegen; DO NOT EDIT.
package soak

import (
	"context"
	"strings"
	"testing"
	"time"
)

func TestSoakSoak015Validate(t *testing.T) {
	m := NewSoakSoak015()
	if err := m.Validate(); err != nil {
		t.Fatalf("validate: %v", err)
	}
}

func TestSoakSoak015Run(t *testing.T) {
	m := NewSoakSoak015()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	out, err := m.Run(ctx, "sample-input-15")
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !strings.Contains(out, m.Name) {
		t.Fatalf("expected name in output, got %q", out)
	}
}

func TestSoakSoak015Snapshot(t *testing.T) {
	m := NewSoakSoak015()
	snap := m.Snapshot()
	if snap["id"] != 15 {
		t.Fatalf("unexpected snapshot id: %v", snap["id"])
	}
}
