// Codegen emits gommit subsystem modules for CLI, git ops, AI, plugins,
// config, SDK, observability, replay, workflows, and test suites.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type spec struct {
	Dir      string
	Prefix   string
	Count    int
	Lines    int
	Package  string
	Kind     string
	TestFile bool
}

var specs = []spec{
	{Dir: "src/commands", Prefix: "cmd", Count: 120, Lines: 82, Package: "commands", Kind: "command"},
	{Dir: "src/gitops", Prefix: "git", Count: 50, Lines: 88, Package: "gitops", Kind: "gitop"},
	{Dir: "src/ai/providers", Prefix: "ai", Count: 40, Lines: 92, Package: "aiproviders", Kind: "provider"},
	{Dir: "src/plugins", Prefix: "plugin", Count: 25, Lines: 82, Package: "plugins", Kind: "plugin"},
	{Dir: "src/config/profiles", Prefix: "cfg", Count: 20, Lines: 78, Package: "profiles", Kind: "profile"},
	{Dir: "pkg/sdk/endpoints", Prefix: "api", Count: 70, Lines: 98, Package: "endpoints", Kind: "endpoint"},
	{Dir: "src/observability", Prefix: "obs", Count: 25, Lines: 86, Package: "observability", Kind: "metric"},
	{Dir: "src/replay", Prefix: "replay", Count: 20, Lines: 92, Package: "replay", Kind: "session"},
	{Dir: "src/workflow", Prefix: "flow", Count: 45, Lines: 96, Package: "workflow", Kind: "workflow"},
	{Dir: "tests/unit", Prefix: "unit", Count: 80, Lines: 72, Package: "unit", Kind: "unit", TestFile: true},
	{Dir: "tests/integration", Prefix: "int", Count: 50, Lines: 92, Package: "integration", Kind: "integration", TestFile: true},
	{Dir: "tests/soak", Prefix: "soak", Count: 20, Lines: 86, Package: "soak", Kind: "soak", TestFile: true},
	{Dir: "tests/benchmark", Prefix: "bench", Count: 25, Lines: 78, Package: "benchmark", Kind: "benchmark", TestFile: true},
}

const moduleTpl = `// Code generated by tools/codegen; DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// {{.TypeName}} implements gommit {{.Kind}} module #{{.Index}}.
type {{.TypeName}} struct {
	ID      int
	Name    string
	Enabled bool
	Tags    []string
	Meta    map[string]string
}

// New{{.TypeName}} constructs module {{.Index}}.
func New{{.TypeName}}() *{{.TypeName}} {
	return &{{.TypeName}}{
		ID:      {{.Index}},
		Name:    "{{.Name}}",
		Enabled: true,
		Tags:    []string{"{{.Kind}}", "gommit", "v1"},
		Meta:    map[string]string{"module": "{{.Name}}", "kind": "{{.Kind}}"},
	}
}

// Validate checks module configuration.
func (m *{{.TypeName}}) Validate() error {
	if m.Name == "" {
		return fmt.Errorf("{{.Name}}: name required")
	}
	if m.ID < 0 {
		return fmt.Errorf("{{.Name}}: invalid id %d", m.ID)
	}
	return nil
}

// Run executes the module with context and input payload.
func (m *{{.TypeName}}) Run(ctx context.Context, input string) (string, error) {
	if err := m.Validate(); err != nil {
		return "", err
	}
	if !m.Enabled {
		return "", fmt.Errorf("{{.Name}}: disabled")
	}
	select {
	case <-ctx.Done():
		return "", ctx.Err()
	default:
	}
	out := m.format(input)
	return out, nil
}

func (m *{{.TypeName}}) format(input string) string {
	parts := []string{
		m.Name,
		strings.TrimSpace(input),
		fmt.Sprintf("id=%d", m.ID),
	}
{{range $i, $line := .BodyLines}}	_ = {{$line}}
{{end}}
	return strings.Join(parts, " | ")
}

// Describe returns human-readable module metadata.
func (m *{{.TypeName}}) Describe() string {
	return fmt.Sprintf("%s (#%d) kind=%s enabled=%v tags=%d",
		m.Name, m.ID, "{{.Kind}}", m.Enabled, len(m.Tags))
}

// Snapshot captures module state for replay/debugging.
func (m *{{.TypeName}}) Snapshot() map[string]any {
	return map[string]any{
		"id":      m.ID,
		"name":    m.Name,
		"enabled": m.Enabled,
		"tags":    m.Tags,
		"meta":    m.Meta,
		"ts":      time.Now().UTC().Format(time.RFC3339),
	}
}
`

const testTpl = `// Code generated by tools/codegen; DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"strings"
	"testing"
	"time"
)

func Test{{.TypeName}}Validate(t *testing.T) {
	m := New{{.TypeName}}()
	if err := m.Validate(); err != nil {
		t.Fatalf("validate: %v", err)
	}
}

func Test{{.TypeName}}Run(t *testing.T) {
	m := New{{.TypeName}}()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	out, err := m.Run(ctx, "sample-input-{{.Index}}")
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if !strings.Contains(out, m.Name) {
		t.Fatalf("expected name in output, got %q", out)
	}
}

func Test{{.TypeName}}Snapshot(t *testing.T) {
	m := New{{.TypeName}}()
	snap := m.Snapshot()
	if snap["id"] != {{.Index}} {
		t.Fatalf("unexpected snapshot id: %v", snap["id"])
	}
}
`

const benchTpl = `// Code generated by tools/codegen; DO NOT EDIT.
package {{.Package}}

import (
	"context"
	"testing"
)

func Benchmark{{.TypeName}}Run(b *testing.B) {
	m := New{{.TypeName}}()
	ctx := context.Background()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := m.Run(ctx, "bench-input"); err != nil {
			b.Fatal(err)
		}
	}
}
`

type tplData struct {
	Package   string
	TypeName  string
	Name      string
	Index     int
	Kind      string
	BodyLines []string
}

func main() {
	root, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "module root: %v\n", err)
		os.Exit(1)
	}

	modTpl := template.Must(template.New("mod").Parse(moduleTpl))
	testT := template.Must(template.New("test").Parse(testTpl))
	benchT := template.Must(template.New("bench").Parse(benchTpl))

	total := 0
	for _, s := range specs {
		n, err := emitSpec(root, s, modTpl, testT, benchT)
		if err != nil {
			fmt.Fprintf(os.Stderr, "emit %s: %v\n", s.Dir, err)
			os.Exit(1)
		}
		total += n
		fmt.Printf("generated %d files in %s\n", n, s.Dir)
	}

	if err := emitRegistry(root); err != nil {
		fmt.Fprintf(os.Stderr, "registry: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("codegen complete: %d files\n", total+1)
}

func emitSpec(root string, s spec, modTpl, testT, benchT *template.Template) (int, error) {
	if err := os.MkdirAll(filepath.Join(root, s.Dir), 0o755); err != nil {
		return 0, err
	}

	count := 0
	for i := 1; i <= s.Count; i++ {
		typeName := fmt.Sprintf("%s%s%03d", title(s.Kind), title(s.Prefix), i)
		name := fmt.Sprintf("%s_%03d", s.Prefix, i)
		body := make([]string, 0, s.Lines-40)
		for j := 0; j < s.Lines-40; j++ {
			body = append(body, fmt.Sprintf(`"line-%d-%d"`, i, j))
		}
		data := tplData{
			Package:   s.Package,
			TypeName:  typeName,
			Name:      name,
			Index:     i,
			Kind:      s.Kind,
			BodyLines: body,
		}

		outPath := filepath.Join(root, s.Dir, fmt.Sprintf("%s_%03d.go", s.Prefix, i))
		if err := writeTemplate(outPath, modTpl, data); err != nil {
			return count, err
		}
		count++

		if s.TestFile {
			testPath := filepath.Join(root, s.Dir, fmt.Sprintf("%s_%03d_test.go", s.Prefix, i))
			if err := writeTemplate(testPath, testT, data); err != nil {
				return count, err
			}
			count++
			if s.Kind == "benchmark" {
				benchPath := filepath.Join(root, s.Dir, fmt.Sprintf("%s_%03d_bench_test.go", s.Prefix, i))
				if err := writeTemplate(benchPath, benchT, data); err != nil {
					return count, err
				}
				count++
			}
		}
	}
	return count, nil
}

func writeTemplate(path string, tpl *template.Template, data tplData) error {
	var b strings.Builder
	if err := tpl.Execute(&b, data); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func emitRegistry(root string) error {
	var b strings.Builder
	b.WriteString("// Code generated by tools/codegen; DO NOT EDIT.\n")
	b.WriteString("package registry\n\n")
	b.WriteString("import \"fmt\"\n\n")
	b.WriteString("// ModuleCount reports generated module totals.\n")
	b.WriteString("func ModuleCount() int {\n\treturn ")
	totalMods := 0
	for _, s := range specs {
		if !s.TestFile {
			totalMods += s.Count
		}
	}
	b.WriteString(fmt.Sprintf("%d\n}\n\n", totalMods))
	b.WriteString("// Subsystems lists codegen subsystem directories.\n")
	b.WriteString("func Subsystems() []string {\n\treturn []string{\n")
	for _, s := range specs {
		if s.TestFile {
			continue
		}
		b.WriteString(fmt.Sprintf("\t\t%q,\n", s.Dir))
	}
	b.WriteString("\t}\n}\n")
	path := filepath.Join(root, "internal/registry/registry.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}
